---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    shell: nohup /apache-tomcat-8.5.51/bin/shutdown.sh 
  - name: Clean the existing war file
    file:
      path: /apache-tomcat-8.5.51/webapps/hello-world-servlet-example.war
      state: absent    
  - name: Deploy War File
    get_url:
       url: http://13.235.42.43:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.geekcap.vmturbo&a=hello-world-servlet-example1&p=war&v=LATEST
       dest: /apache-tomcat-8.5.51/webapps/hello-world-servlet-example1.war
  - name: start tomcat
    shell: nohup /apache-tomcat-8.5.51/bin/startup.sh 
